# Настройки окна
WIN_WIDTH, WIN_HEIGHT = 960, 540
DISPLAY_SIZE = (WIN_WIDTH, WIN_HEIGHT)
FULL_SCREEN = False
MENU_TITLE = 'Название игры'
FPS = 60
# Цвета
SECTORS_BACKGROUND_COLOR = '#6e0c16'
BACKGROUND_COLOR = "#004400"
CELL_COLOR = '#013a33'
# Камера
CAMERA_SPEED_X, CAMERA_SPEED_Y = 3, 2
# Ячейки
SIZE_CELL = 40
