# Настройки окна
WIN_WIDTH, WIN_HEIGHT = 1920, 1080
DISPLAY_SIZE = (WIN_WIDTH, WIN_HEIGHT)
FULL_SCREEN = False
MENU_TITLE = 'Название игры'
FPS = 60
# Цвета
SECTORS_BACKGROUND_COLOR = '#6e0c16'
BACKGROUND_COLOR = "#004400"
CELL_COLOR = '#013a33'
# Камера
CAMERA_SPEED_X, CAMERA_SPEED_Y = 33, 22
# Ячейки
COEFFICIENT_SCALE = 5
CELL_SIZE = 130
CELL_Y_NUMBER = 50
CELL_X_NUMBER = 50
