# robot1 = Robot(pos=(1, 1), size_cell=self.size_cell)
# sector.entities.add(robot1)
# robot2 = Robot(pos=(2, 1), size_cell=self.size_cell)
# sector.entities.add(robot2)
# sector.place_base(pos=(8, 12))
base.create_robot(MK0)
